version: '3'
services:
  db:
    image: mysql:8.4.2
    command: --mysql-native-password=ON
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petadoption
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: